test_average (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... ok
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... ok

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 62, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [(114.59155902616465, 6875.493541569878, 24[197 chars]745)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902616465, 6875.493541569878, 24751776.749651562)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902616465, 6875.493541569878, 24751776.749651562),
-  (-229.1831180523293, -13750.987083139757, -49503553.499303125),
-  (286.4788975654116, 17188.733853924696, 61879441.87412891),
-  (234.3397382085067, 14060.384292510402, 50617383.45303745)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=1)
